import { createGlobalTheme } from "@vanilla-extract/css";
import { BRAND_PALETTE } from "../data/brand";

/** Semantic roles keep the page, panels, artwork stages and interactive states consistent. */
export const vars = createGlobalTheme(":root", {
  color: {
    canvas: BRAND_PALETTE.canvas,
    surface: BRAND_PALETTE.surface,
    raised: BRAND_PALETTE.raised,
    text: BRAND_PALETTE.ink,
    muted: BRAND_PALETTE.muted,
    line: `${BRAND_PALETTE.ink}28`,
    accent: BRAND_PALETTE.oak,
    focus: BRAND_PALETTE.oak,
    imageOverlay: `${BRAND_PALETTE.canvas}e6`,
  },
  font: { display: '"Outfit", sans-serif', body: '"Outfit", sans-serif' },
  fontSize: {
    tiny: "0.78rem",
    small: "0.9rem",
    body: "1rem",
    lead: "1.2rem",
    heading: "clamp(2.5rem, 4.5vw, 4rem)",
    subheading: "1.5rem",
    title: "clamp(3rem, 6vw, 5rem)",
    catalog: "clamp(1.75rem, 3vw, 2.5rem)",
    hero: "clamp(2.6rem, 5vw, 4.6rem)",
  },
  weight: { body: "400", medium: "500", strong: "600", display: "600" },
  line: { body: "1.55", heading: "1.05" },
  tracking: { heading: "-0.035em", label: "0.06em" },
  space: {
    none: "0",
    xxs: "0.25rem",
    xs: "0.5rem",
    sm: "0.75rem",
    md: "1rem",
    lg: "1.5rem",
    xl: "2rem",
    xxl: "3rem",
    xxxl: "4rem",
    section: "clamp(4rem, 7vw, 6rem)",
    gutter: "clamp(1.25rem, 4vw, 3.5rem)",
  },
  radius: { small: "0.625rem", scene: "1.5rem", pill: "999rem" },
  size: {
    content: "78rem",
    copy: "34rem",
    reading: "46rem",
    compactLogo: "16rem",
    emblem: "2.75rem",
    icon: "1.2rem",
    border: "0.0625rem",
    focus: "0.1875rem",
    button: "3rem",
    header: "5rem",
    photo: "27rem",
    mobilePhoto: "17rem",
    outline: "0.125rem",
    brandTile: "16rem",
    mobileLogo: "8rem",
    wordmarkPreview: "24rem",
    iconPreview: "10rem",
    heroPhoto: "34rem",
    timberWordmark: "48rem",
    timberPanorama: "22rem",
    studyIcon: "4rem",
    studyArtwork: "12rem",
    studyIntro: "8rem",
    studyWordmark: "16rem",
    studyWordmarkMobile: "8rem",
    timberSplitWordmark: "24rem",
    backdropWordmark: "32rem",
    backdropHero: "41rem",
    headerIcon: "2rem",
  },
  motion: { short: "180ms", ease: "cubic-bezier(0.2, 0.8, 0.2, 1)" },
});

export const breakpoint = {
  compact: "screen and (max-width: 64rem)",
  narrow: "screen and (max-width: 44rem)",
} as const;
