import { createGlobalTheme } from "@vanilla-extract/css";

/** Hearth and horizon: the shared website and brand-kit design system. */
export const vars = createGlobalTheme(":root", {
  color: {
    mist: "#eef3ed",
    pine: "#23483f",
    meadow: "#9cba9e",
    honey: "#f5c45b",
    sky: "#cddfe7",
    white: "#ffffff",
    muted: "#586d63",
    line: "#d1dbd1",
    soft: "#e0e9df",
    deep: "#16372f",
    lightText: "#d3e1d5",
    focus: "#386eae",
  },
  font: { display: '"Bricolage Grotesque", sans-serif', body: '"Outfit", sans-serif' },
  fontSize: {
    tiny: "0.78rem",
    small: "0.9rem",
    body: "1rem",
    lead: "1.2rem",
    heading: "clamp(2.5rem, 5vw, 4.5rem)",
    hero: "clamp(3.65rem, 7vw, 6.5rem)",
    subheading: "1.5rem",
    brand: "clamp(3rem, 8vw, 7rem)",
  },
  weight: { body: "400", medium: "500", strong: "600", display: "700" },
  line: { body: "1.55", heading: "1.04", hero: "0.97" },
  tracking: { heading: "-0.045em", label: "0.07em" },
  space: {
    none: "0",
    xxs: "0.25rem",
    xs: "0.5rem",
    sm: "0.75rem",
    md: "1rem",
    lg: "1.5rem",
    xl: "2rem",
    xxl: "3rem",
    xxxl: "4rem",
    section: "clamp(4rem, 8vw, 7rem)",
    gutter: "clamp(1.25rem, 5vw, 5rem)",
  },
  radius: { small: "0.5rem", panel: "1.5rem", large: "2.5rem", pill: "999rem" },
  size: {
    content: "82rem",
    copy: "34rem",
    reading: "46rem",
    brand: "10rem",
    footerBrand: "12rem",
    icon: "1.2rem",
    bigIcon: "2rem",
    logoIcon: "5rem",
    border: "0.0625rem",
    focus: "0.1875rem",
    button: "3.1rem",
    header: "5.8rem",
    atlas: "27rem",
    mobileAtlas: "18rem",
    art: "48rem",
    heroCopy: "32rem",
    headerGap: "2.5rem",
    illustrationLabel: "14rem",
    tile: "4rem",
  },
  shadow: { action: "0 0.25rem 0 #deb052", panel: "0 1rem 3rem #23483f0a" },
  motion: { short: "180ms", medium: "400ms", ease: "cubic-bezier(0.2, 0.8, 0.2, 1)" },
});

/** Layout changes follow the content rather than a particular device. */
export const breakpoint = {
  compact: "screen and (max-width: 64rem)",
  narrow: "screen and (max-width: 44rem)",
} as const;
