modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Quzzar/kithkyn/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://kithkyn.com/updates.json"
displayURL="https://kithkyn.com"
logoFile="kithkyn-logo.png"
credits="Architecture inspired by Towns and Towers (Biban_Auriu, Kubek, Cristelknight, William Wythers), Dungeons and Taverns (Nova_Wostra, Konci, WhityLee), ChoiceTheorem's Overhauled Village, and Unstructured (Cristelknight, Delta_Kaktus, Biban_Auriu). Built with Llama. See README for model terms."
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
